# Generated by Django 4.2.6 on 2023-10-22 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flash_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardName', models.CharField(max_length=50)),
                ('ImageUrl', models.URLField()),
                ('Worth', models.FloatField(max_length=15)),
                ('price', models.FloatField(max_length=15)),
                ('discount', models.FloatField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='User',
            new_name='user',
        ),
    ]
