# Generated by Django 4.2.6 on 2023-10-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderitem_flash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='flash',
        ),
    ]
