# Generated by Django 4.2.6 on 2023-10-30 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_orderitem_flash'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='flash',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.flash_sales'),
        ),
    ]
