# Generated by Django 4.2.6 on 2023-12-04 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customer_isexisting_customer_isnew_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='offer',
            new_name='isSold',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sold',
            new_name='onOffer',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='value',
        ),
        migrations.AddField(
            model_name='product',
            name='cardNo',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='cardPin',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='emailAddress',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='passWord',
            field=models.CharField(default=None, max_length=200, null=True),
        ),

        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
