# Generated by Django 4.2.6 on 2023-12-04 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_rename_offer_product_issold_and_more'),
    ]

    operations = [

    ]
