# Generated by Django 4.2.6 on 2023-12-04 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_product_sellingprice'),
    ]

    operations = [

    ]
