# Generated by Django 4.2.6 on 2023-12-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_product_sellingprice'),
    ]

    operations = [

    ]
