# Generated by Django 4.2.6 on 2023-12-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_sellingprice'),
    ]

    operations = [

    ]
