# Generated by Django 4.2.6 on 2023-12-04 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_sellingprice'),
    ]

    operations = [
 
    ]
