# Generated by Django 4.2.6 on 2023-12-04 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='priceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='cartegories',
            name='value',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.pricevalue'),
        ),
        migrations.AlterField(
            model_name='cartegories',
            name='cardName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_name', to='store.cartegories', to_field='cardName'),
        ),

    ]
