# Generated by Django 4.2.6 on 2023-12-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_pricevalue_alter_cartegories_cardname_and_more'),
    ]

    operations = [

    ]
