# Generated by Django 4.2.6 on 2023-12-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_value2_alter_product_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartegories',
            name='cardName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_name', to='store.cartegories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='value2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_by_value', to='store.cartegories'),
        ),
    ]
