# Generated by Django 4.2.6 on 2023-12-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_product_value2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cardNo',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='cardPin',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='emailAddress',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
    ]
