# Generated by Django 4.2.6 on 2023-12-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_product_cardno_alter_product_cardpin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='passWord',
            field=models.CharField(default='N/A', max_length=200, null=True),
        ),
    ]
